### ISSUE TITLE
Does not stop people from getting the same receiver from the previous year

### ISSUE THREAD

**Issue by jackleland** [jackleland/SuperSecretSantaScript#1]
See title

**Comment by mattjurenka** [comment]
Would it be ok if I took this on as my first issue?

**Comment by jackleland** [comment]
Seems I may have misused that label, you're welcome to give it a go though. How would you go about it?

**Comment by mattjurenka** [comment]
I think that if you remove the is_good2 = True and if banned: lines within the secretsantify method it should work. I unfortunately havent had access to a computer today so I cant test it.

**Comment by jackleland** [comment]
Realised this is already incorporated. Closing the issue.
